import './js/API/API';
import './js/helpers/notifix-init';
import './js/firebase/firebase-init';
import './js/firebase/firebase-auth';
import './js/firebase/firebase-data';
import './js/my-library';
import './js/components/light-dark';
import './js/team-modal';
import './js/team-render';
